# Generated by Django 4.2.2 on 2023-10-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_histransction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histransction',
            old_name='unita',
            new_name='consommation',
        ),
    ]
