# Generated by Django 4.2.2 on 2023-10-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_rename_unit_categorie_souscategorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histransction',
            old_name='consommation',
            new_name='categorie',
        ),
        migrations.AddField(
            model_name='histransction',
            name='souscategorie',
            field=models.CharField(default='', max_length=50),
        ),
    ]
