# Generated by Django 4.2.2 on 2023-10-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_masrif'),
    ]

    operations = [
        migrations.AddField(
            model_name='histransction',
            name='saved_in_masrif',
            field=models.BooleanField(default=False),
        ),
    ]
